# CC=g++
CFLAGS=-O3 -I../../leveldb

# db_test: db_test.cpp
# 	$(CC) -o db_test db_test.cpp $(CFLAGS)
skiplist_test: skiplist_test.cc makefile
	g++ skiplist_test.cc -o skiplist_test -std=c++11 $(CFLAGS)